dns_variable: "frontend-prod.batch7.online"
OVH_ENDPOINT: "ovh-eu"
OVH_APPLICATION_KEY: "$OVH_APPLICATION_KEY"
OVH_APPLICATION_SECRET: "$OVH_APPLICATION_SECRET"
OVH_CONSUMER_KEY: "$OVH_CONSUMER_KEY"