# Install Cypress, then run all tests (in parallel)
stages:
  - build
  - test

# Install NPM dependencies and Cypress
install:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: build

  script:
    - npm install
    - npm run build
    - npm start &
    - npm test

#api-tests:
#  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
#  stage: test
#  parallel: 5
#  script:
#    - npm start:ci & npx wait-on http://localhost:3000
#   - npx cypress run --record --parallel --browser chrome --group "API" --spec "cypress/tests/api/*"

#ui-chrome:
#  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
#  stage: test
#  parallel: 5
#  script:
#    - npm start:ci & npx wait-on http://localhost:3000
#    - npx cypress run --record --parallel --browser chrome --group "UI - Chrome" --spec "cypress/tests/ui/*"

#ui-chrome-mobile:
#  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
#  stage: test
#  parallel: 5
#  script:
#    - npm start:ci & npx wait-on http://localhost:3000
#    - npx cypress run --record --parallel --browser chrome --group "UI - Chrome - Mobile" --spec "cypress/tests/ui/*" --config "viewportWidth=375,viewportHeight=667"

#ui-firefox:
#  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
#  stage: test
#  parallel: 5
#  script:
#    - npm start:ci & npx wait-on http://localhost:3000
#    - npx cypress run --record --parallel --browser firefox --group "UI - Firefox" --spec "cypress/tests/ui/*"

#ui-firefox-mobile:
#  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
#  stage: test
#  parallel: 5
#  script:
#    - npm start:ci & npx wait-on http://localhost:3000
#    - npx cypress run --record --parallel --browser firefox --group "UI - Firefox - Mobile" --spec "cypress/tests/ui/*" --config "viewportWidth=375,viewportHeight=667"
