FROM node:16.20.2-buster
COPY . .
RUN sed -i 's/morningnews.obadasoussachaddad.fr/backendpreprod.obadasoussachaddad.fr/g' /home/engineer/Bureau/Batch7/Projet/morningnews-projet/frontend/components/Article.js
RUN sed -i 's/morningnews.obadasoussachaddad.fr/backendpreprod.obadasoussachaddad.fr/g' /home/engineer/Bureau/Batch7/Projet/morningnews-projet/frontend/components/Header.js
RUN sed -i 's/morningnews.obadasoussachaddad.fr/backendpreprod.obadasoussachaddad.fr/g' /home/engineer/Bureau/Batch7/Projet/morningnews-projet/frontend/components/Home.js
RUN sed -i 's/morningnews.obadasoussachaddad.fr/backendpreprod.obadasoussachaddad.fr/g' /home/engineer/Bureau/Batch7/Projet/morningnews-projet/frontend/components/TopArticle.js
RUN yarn install
RUN yarn run build
EXPOSE 3000
CMD ["npm", "start"]