aws_access_key= #to define
aws_secret_key= #to define
aws_region= "eu-north-1"
aws_key_name= "frontend"
aws_public_key= file("~/.ssh/frontend.pub")
aws_allocation_id= "eipalloc-0eb09a9d11e27c737"
aws_ami= "ami-0506d6d51f1916a96"
aws_instance_type= "t3.micro"
aws_frontend_instance_name= "frontend_preprod"
aws_security_group_name= "frontend_security"